### ISSUE TITLE
FontsAwesome icons not rendering properly

### ISSUE THREAD

**Issue by rh3xp** [Git-Commit-Show/homepage#1]
Check index.html
The links for the top contributor are not rendering the fonts and if they are being rendered, they are not in line.

**Comment by gitcommitshow** [comment]
[Fixed in the master branch](https://github.com/Git-Commit-Show/homepage/commit/e7a1d825d882d581b72ba7f95a9f2b1374ba9aed). Make sure to pull before commit.
